### ISSUE TITLE
Dynamic breadcrumb not shown in {{ breadcrumbs() }}

### ISSUE THREAD

**Issue by KevinSleegers** [thormeier/breadcrumb-bundle#12]
Hi,

At the moment I'm adding breadcrumbs for dynamic routes like this:

```
$this->get('thormeier_breadcrumb.breadcrumb_provider')
            ->getBreadcrumbByRoute('release_notes_show')
            ->setRouteParameters(array(
                'id' => $entity->getId(),
            ))
            ->setLabelParameters(array(
                'name' => $entity->getTitle()
            ));
```

However, when I use `{{ breadcrumbs() }}` in my twig template, that route is not there.

**Comment by thormeier** [comment]
Could you please provide the tree of routes you're having, where you define the breadcrumb? Maybe there's an error there.

**Comment by thormeier** [comment]
@KevinSleegers Since this issue is a few months old now, does the problem still persist?

**Comment by thormeier** [comment]
@KevinSleegers I suppose this issue does not persist, as I haven't heard of you yet. Will therefore close it. Please reopen, if it persists.
