### ISSUE TITLE
modelClass is not used at generateBreadcrumbCollectionFromRequest of Provider

### ISSUE THREAD

**Issue by dmytrof** [thormeier/breadcrumb-bundle#15]
Fix, please:
```
private function generateBreadcrumbCollectionFromRequest()
    {
        /*.......*/
                $collection->addBreadcrumb(new Breadcrumb(
                    $rawCrumb['label'], $rawCrumb['route']
                ));
        /*.........*/
    }
```

**Comment by thormeier** [comment]
@dmytrofeshchenko Fixed with 74ca6495cc46c91ec6335e9f57bcafc7f2b32695, could you please verify that it works now as expected?

**Comment by dmytrof** [comment]
Hello Pascal!

Thanks for update! Could you please set a tag for updating by composer? 

Thanks:)



Monday, December 12, 2016, 2:26:35 PM, you wrote:


@dmytrofeshchenko Fixed with 74ca649, could you please verify that it works now as expected?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



-----------------------------------------------
С уважением,
Дмитрий Фещенко
Менеджер проектов
DF-Studio - Лучшие решения для Вашего бизнеса!

**Comment by thormeier** [comment]
@dmytrofeshchenko You're very welcome, thank you for the report! Tagged at 2.1.3. If everythings fine, I'll close this issue.

**Comment by dmytrof** [comment]
Hello Pascal,

All is working fine. Thank you!:)


Tuesday, December 20, 2016, 1:14:37 PM, you wrote:


@dmytrofeshchenko You're very welcome, thank you for the report! Tagged at 2.1.3. If everythings fine, I'll close this issue.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



-----------------------------------------------
С уважением,
Дмитрий Фещенко
Менеджер проектов
DF-Studio - Лучшие решения для Вашего бизнеса!
