### ISSUE TITLE
Twig replace now take an array parameter

### ISSUE THREAD

**Issue by yannbertrand** [thormeier/breadcrumb-bundle#19]
The `replace('%%', '%')` is deprecated (since twig@1.22) and is removed in twig@2.0.

Updating it by `replace({ '%%': '%' })` fixes this :smile: .

https://stackoverflow.com/questions/33891023/deprecation-of-twig-filters-use-twig-simplefilter-instead

**Comment by thormeier** [comment]
Thank you for reporting, I'll fix this within the next few days :)

**Comment by thormeier** [comment]
Hello, unfortunately I wasn't able to find time to fix this issue yet and I'm sorry for that. I'm not as active on this project as I want to be, so maybe you could open a PR to fix this issue?

**Comment by iainhallam** [comment]
Is there any chance of this being merged into the main repo, please? Working with Symfony 4 this now presents an error using this bundle. A tagged release would also be welcome. Thanks!

**Comment by thormeier** [comment]
Just merged the PR. Thank you for your patience. I'm sorry for almost abandoning this project, I just haven't had the time to do anything since I started studying for my BSc.

Could this issue be resolved?

**Comment by thormeier** [comment]
@iainhallam Added a tagged release: https://github.com/thormeier/breadcrumb-bundle/tree/2.2.0

**Comment by yannbertrand** [comment]
Hey! No need to excuse.

You are probably working on totally different stuff now (I have not been using Symfony since then).

You did your best at the time and it has been really useful. I'm really thankful for the work you did and lots of other persons probably are as well 😄

Thanks for closing this issue ❤️!
