### ISSUE TITLE
deprecation error routing.loader

### ISSUE THREAD

**Issue by marco-mdl** [thormeier/breadcrumb-bundle#20]
Hi,

I get an error

`[
  "exception" => ErrorException {
    #message: "User Deprecated: The "routing.loader" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead."
    #code: 0
    #file: "./vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php"
    #line: 275
    #severity: E_USER_DEPRECATED
    trace: {
      ./vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php:56 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:367 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:289 { …}
      Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}() {}
      ./vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCacheFactory.php:43 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:302 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php:73 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/RouterCacheWarmer.php:55 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:52 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:207 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:166 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:121 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:252 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:936 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:83 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:222 { …}
      ./vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:71 { …}
      ./vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:129 { …}
      ./bin/console:28 {
        › $application = new Application($kernel);
        › $application->run($input);
        ›
      }
    }
  }
]
`

because of this "$container->setAlias('routing.loader', 'thormeier_breadcrumb.routing.attach_breadcrumb_loader');"

see [https://github.com/symfony/symfony/issues/24886](https://github.com/symfony/symfony/issues/24886)

**Comment by thormeier** [comment]
Just merged the PR that fixes this.
