### ISSUE TITLE
Configuration with annotation

### ISSUE THREAD

**Issue by jeremy-rafflin** [thormeier/breadcrumb-bundle#22]
Hi, is it possible to configure the breadcrum with annotation ?

**Comment by joezg** [comment]
It seems that it is possible.
This is how I made it work:
`* @Route("/course/{courseId}", name="course", options={ "breadcrumb" = { "label" = "Course", "parent_route" = "courses" }})`

**Comment by thormeier** [comment]
Thank you for pointing this out! Added an example to README.
