### ISSUE TITLE
`routing.loader` service is private deprecation in Symfony 3.4

### ISSUE THREAD

**Issue by karkadann** [thormeier/breadcrumb-bundle#23]
When decorating routing.loader in a compiler pass I get the following deprecation error when the container is built:

![32618918-0d6df242-c547-11e7-94d2-30562215dee0](https://user-images.githubusercontent.com/11688669/36023241-10ad62a2-0d8c-11e8-9e55-3ec231f63e4d.png)

**Comment by thormeier** [comment]
Just merged the PR that fixes this.
