### ISSUE TITLE
Tree builder without a root node is deprecated since Symfony 4.2

### ISSUE THREAD

**Issue by iainhallam** [thormeier/breadcrumb-bundle#26]
Using this bundle in Symfony 4.2, I now get the deprecation warning:

`A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.`

The warning is generated by line 20 of this file:

`thormeier\breadcrumb-bundle\DependencyInjection\Configuration.php`

**Comment by thormeier** [comment]
Fixed with https://github.com/thormeier/breadcrumb-bundle/tree/2.2.1
